<a href="https://colab.research.google.com/github/BYEONGSEOKKIM/python/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

%precision 3
pd.set_option('precision',3)

In [11]:
df = pd.read_excel('notExercise.xls')
df

      기간    대분류            분류  ...  운동을 할 만한 장소가 없어서 운동을 싫어해서    기타
0   2017    서울시           서울시  ...               5.8     34.7   1.7
1   2017     성별            남자  ...               5.5     29.8   1.6
2   2017     성별            여자  ...               6.0     38.8   1.8
3   2017    연령별           10대  ...               5.6     32.2   0.3
4   2017    연령별           20대  ...               5.2     32.9   0.1
5   2017    연령별           30대  ...               4.6     31.6   0.2
6   2017    연령별           40대  ...               5.2     29.4     1
7   2017    연령별           50대  ...               7.2     32.2   1.4
8   2017    연령별        60대 이상  ...               6.9     46.8     6
9   2017    학력별         중졸 이하  ...               6.6     46.2   7.4
10  2017    학력별         고졸 이하  ...               6.9     36.5   1.7
11  2017    학력별         대졸 이하  ...               4.9     30.7   0.4
12  2017    학력별        대학원 이상  ...               0.6     29.6   0.6
13  2017    소득별      100만원 미만  ...               3.6     50.7  12.7
14  2017    소득별  100-200만원 미만  ...               7.1     41.5   5.6
15  2017    소득별  200-300만원 미만  ...               6.8     30.7   1.4
16  2017    소득별  300-400만원 미만  ...               6.5     31.2   0.3
17  2017    소득별  400-500만원 미만  ...               5.3     33.0   0.6
18  2017    소득별      500만원 이상  ...               5.1     34.9   0.6
19  2017  혼인상태별            기혼  ...               5.4     34.9   1.2
20  2017  혼인상태별            미혼  ...               5.4     32.2     1
21  2017  혼인상태별         이혼/별거  ...               6.8     34.9   2.7
22  2017  혼인상태별            사별  ...               8.9     42.9     8
23  2017  지역대분류           도심권  ...               4.5     36.4   1.7
24  2017  지역대분류           동북권  ...               5.9     36.1   2.7
25  2017  지역대분류           서북권  ...               7.4     28.5   0.8
26  2017  지역대분류           서남권  ...               5.7     35.0   1.9
27  2017  지역대분류           동남권  ...               4.9     35.4   0.6
28  2017    종로구           종로구  ...               7.8     32.4   0.2
29  2017     중구            중구  ...               1.9     40.5   5.5
30  2017    용산구           용산구  ...               4.3     36.0     -
31  2017    성동구           성동구  ...               6.8     37.8     -
32  2017    광진구           광진구  ...               5.6     32.5   4.4
33  2017   동대문구          동대문구  ...               3.4     43.6   4.2
34  2017    중랑구           중랑구  ...               5.7     42.0   0.4
35  2017    성북구           성북구  ...               6.1     33.4     1
36  2017    강북구           강북구  ...               6.7     37.7     -
37  2017    도봉구           도봉구  ...               5.1     32.0   2.3
38  2017    노원구           노원구  ...               7.2     32.5   7.9
39  2017    은평구           은평구  ...               7.1     29.7   0.8
40  2017   서대문구          서대문구  ...               7.9     27.3   0.5
41  2017    마포구           마포구  ...               7.5     28.0   1.2
42  2017    양천구           양천구  ...              10.6     22.3   0.3
43  2017    강서구           강서구  ...               4.0     27.1   1.6
44  2017    구로구           구로구  ...               7.3     43.3   0.4
45  2017    금천구           금천구  ...               3.2     46.1   0.5
46  2017   영등포구          영등포구  ...               4.0     34.8     4
47  2017    동작구           동작구  ...               1.1     47.0   5.9
48  2017    관악구           관악구  ...               6.9     33.6   1.7
49  2017    서초구           서초구  ...               3.2     32.0   1.5
50  2017    강남구           강남구  ...               2.6     31.5   1.3
51  2017    송파구           송파구  ...               5.8     44.3   0.1
52  2017    강동구           강동구  ...               6.8     30.4   0.1

[53 rows x 8 columns]

In [12]:
df.drop(columns= '기간', inplace=True)
df

      대분류            분류  운동을 할 충분한 시간이 없어서  ... 운동을 할 만한 장소가 없어서  운동을 싫어해서    기타
0     서울시           서울시               49.7  ...              5.8      34.7   1.7
1      성별            남자               55.2  ...              5.5      29.8   1.6
2      성별            여자               45.0  ...              6.0      38.8   1.8
3     연령별           10대               55.7  ...              5.6      32.2   0.3
4     연령별           20대               54.8  ...              5.2      32.9   0.1
5     연령별           30대               58.1  ...              4.6      31.6   0.2
6     연령별           40대               57.7  ...              5.2      29.4     1
7     연령별           50대               50.1  ...              7.2      32.2   1.4
8     연령별        60대 이상               27.5  ...              6.9      46.8     6
9     학력별         중졸 이하               26.1  ...              6.6      46.2   7.4
10    학력별         고졸 이하               46.3  ...              6.9      36.5   1.7
11    학력별         대졸 이하               57.4  ...              4.9      30.7   0.4
12    학력별        대학원 이상               65.3  ...              0.6      29.6   0.6
13    소득별      100만원 미만               22.7  ...              3.6      50.7  12.7
14    소득별  100-200만원 미만               34.3  ...              7.1      41.5   5.6
15    소득별  200-300만원 미만               48.8  ...              6.8      30.7   1.4
16    소득별  300-400만원 미만               54.9  ...              6.5      31.2   0.3
17    소득별  400-500만원 미만               56.1  ...              5.3      33.0   0.6
18    소득별      500만원 이상               52.3  ...              5.1      34.9   0.6
19  혼인상태별            기혼               50.7  ...              5.4      34.9   1.2
20  혼인상태별            미혼               54.3  ...              5.4      32.2     1
21  혼인상태별         이혼/별거               47.4  ...              6.8      34.9   2.7
22  혼인상태별            사별               25.2  ...              8.9      42.9     8
23  지역대분류           도심권               50.5  ...              4.5      36.4   1.7
24  지역대분류           동북권               47.4  ...              5.9      36.1   2.7
25  지역대분류           서북권               49.4  ...              7.4      28.5   0.8
26  지역대분류           서남권               50.7  ...              5.7      35.0   1.9
27  지역대분류           동남권               52.2  ...              4.9      35.4   0.6
28    종로구           종로구               41.4  ...              7.8      32.4   0.2
29     중구            중구               51.0  ...              1.9      40.5   5.5
30    용산구           용산구               55.9  ...              4.3      36.0     -
31    성동구           성동구               50.5  ...              6.8      37.8     -
32    광진구           광진구               49.1  ...              5.6      32.5   4.4
33   동대문구          동대문구               47.2  ...              3.4      43.6   4.2
34    중랑구           중랑구               47.9  ...              5.7      42.0   0.4
35    성북구           성북구               43.4  ...              6.1      33.4     1
36    강북구           강북구               48.4  ...              6.7      37.7     -
37    도봉구           도봉구               52.0  ...              5.1      32.0   2.3
38    노원구           노원구               44.6  ...              7.2      32.5   7.9
39    은평구           은평구               44.8  ...              7.1      29.7   0.8
40   서대문구          서대문구               58.6  ...              7.9      27.3   0.5
41    마포구           마포구               47.7  ...              7.5      28.0   1.2
42    양천구           양천구               55.2  ...             10.6      22.3   0.3
43    강서구           강서구               59.0  ...              4.0      27.1   1.6
44    구로구           구로구               42.9  ...              7.3      43.3   0.4
45    금천구           금천구               42.4  ...              3.2      46.1   0.5
46   영등포구          영등포구               53.8  ...              4.0      34.8     4
47    동작구           동작구               46.0  ...              1.1      47.0   5.9
48    관악구           관악구               50.7  ...              6.9      33.6   1.7
49    서초구           서초구               59.8  ...              3.2      32.0   1.5
50    강남구           강남구               59.1  ...              2.6      31.5   1.3
51    송파구           송파구               42.6  ...              5.8      44.3   0.1
52    강동구           강동구               53.1  ...              6.8      30.4   0.1

[53 rows x 7 columns]

In [13]:
df['대분류'][23:]

23    지역대분류
24    지역대분류
25    지역대분류
26    지역대분류
27    지역대분류
28      종로구
29       중구
30      용산구
31      성동구
32      광진구
33     동대문구
34      중랑구
35      성북구
36      강북구
37      도봉구
38      노원구
39      은평구
40     서대문구
41      마포구
42      양천구
43      강서구
44      구로구
45      금천구
46     영등포구
47      동작구
48      관악구
49      서초구
50      강남구
51      송파구
52      강동구
Name: 대분류, dtype: object

In [14]:
df.drop(index=range(23,52), inplace = True)
df

      대분류            분류  운동을 할 충분한 시간이 없어서  ... 운동을 할 만한 장소가 없어서  운동을 싫어해서    기타
0     서울시           서울시               49.7  ...              5.8      34.7   1.7
1      성별            남자               55.2  ...              5.5      29.8   1.6
2      성별            여자               45.0  ...              6.0      38.8   1.8
3     연령별           10대               55.7  ...              5.6      32.2   0.3
4     연령별           20대               54.8  ...              5.2      32.9   0.1
5     연령별           30대               58.1  ...              4.6      31.6   0.2
6     연령별           40대               57.7  ...              5.2      29.4     1
7     연령별           50대               50.1  ...              7.2      32.2   1.4
8     연령별        60대 이상               27.5  ...              6.9      46.8     6
9     학력별         중졸 이하               26.1  ...              6.6      46.2   7.4
10    학력별         고졸 이하               46.3  ...              6.9      36.5   1.7
11    학력별         대졸 이하               57.4  ...              4.9      30.7   0.4
12    학력별        대학원 이상               65.3  ...              0.6      29.6   0.6
13    소득별      100만원 미만               22.7  ...              3.6      50.7  12.7
14    소득별  100-200만원 미만               34.3  ...              7.1      41.5   5.6
15    소득별  200-300만원 미만               48.8  ...              6.8      30.7   1.4
16    소득별  300-400만원 미만               54.9  ...              6.5      31.2   0.3
17    소득별  400-500만원 미만               56.1  ...              5.3      33.0   0.6
18    소득별      500만원 이상               52.3  ...              5.1      34.9   0.6
19  혼인상태별            기혼               50.7  ...              5.4      34.9   1.2
20  혼인상태별            미혼               54.3  ...              5.4      32.2     1
21  혼인상태별         이혼/별거               47.4  ...              6.8      34.9   2.7
22  혼인상태별            사별               25.2  ...              8.9      42.9     8
52    강동구           강동구               53.1  ...              6.8      30.4   0.1

[24 rows x 7 columns]

In [16]:
df_s = df[df['대분류'] == '성별'].copy()
df_s

  대분류  분류  운동을 할 충분한 시간이 없어서 함께 운동을 할 사람이 없어서  운동을 할 만한 장소가 없어서  운동을 싫어해서   기타
1  성별  남자               55.2              7.9               5.5      29.8  1.6
2  성별  여자               45.0              8.3               6.0      38.8  1.8

In [17]:
df_s.drop(columns='대분류', inplace=True)
df_s

   분류  운동을 할 충분한 시간이 없어서 함께 운동을 할 사람이 없어서  운동을 할 만한 장소가 없어서  운동을 싫어해서   기타
1  남자               55.2              7.9               5.5      29.8  1.6
2  여자               45.0              8.3               6.0      38.8  1.8

In [20]:
df_s.set_index('분류', inplace=True)
df_s

    운동을 할 충분한 시간이 없어서 함께 운동을 할 사람이 없어서  운동을 할 만한 장소가 없어서  운동을 싫어해서   기타
분류
남자               55.2              7.9               5.5      29.8  1.6
여자               45.0              8.3               6.0      38.8  1.8